# Generated by Django 2.0 on 2017-12-03 15:59

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductManager',
        ),
        migrations.AlterModelManagers(
            name='product',
            managers=[
                ('products', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='sku',
            managers=[
                ('available_skus', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='sku',
            name='price',
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=2199, max_digits=20),
            preserve_default=False,
        ),
    ]
